# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180626_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
