# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_address_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='address',
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
